### ISSUE TITLE
Final Project - Step 3

### ISSUE THREAD

**Issue by Mazhar3204** [Watts-College/paf-514-template#59]
Hi professor, @lecy 
I am trying to work on the salary-report.rmd file. 

I have it set up like this:

```
---
title: 'ASU Salary Report'
output:
  html_document:
    theme: readable
    highlight: zenburn
    toc: true
params:
  url:
    value: x   
---
```

<br>
<hr>
<br>

### Example Report Assets Section 

```{r setup, include=FALSE}
knitr::opts_chunk$set( echo = TRUE, message=F, warning=F )
```

```
# Be sure to hide all of the extra messages and code in the final report:
# ```{r setup, include=FALSE}
# knitr::opts_chunk$set( echo = F, message=F, warning=F )
# ```
```

```{r libraries}
# LOAD PACKAGES
library( dplyr )
library( pander )
library( knitr )
library( gender )
library(readr)

# SOURCE CUSTOM FUNCTIONS
source( "utils.R" )
```

```{r data}
# LOAD DATA
URL <- params$url
d <- read.csv( URL )
```

However, when I run the load data, I get this error. 

```
Error in file(file, "rt") : cannot open the connection
```

I checked the URLs, and it ran perfectly, and I checked the batch.r file is in the working directory. I am not sure why it isn't pulling it.
